### PR TITLE
Added user auth

### PR DESCRIPTION
**Pull request by Radicitus**
It works however it overwrites the auth page someone wrote and I'm not sure how. I think it programatically created its own story board from the code I found, so need to figure that out.

### CODE REVIEW

**Comment by Carminiumn** [comment]
Looks good for me, but since it redirects to the Spotify app every time, the simulator will crash and a real iPhone is needed for the test. Redirect to a web page and open safari could be a better choice but I'm not sure if we have enough time. If @alyssaharveey is good with this then just merge it.

**Comment by alyssaharveey** [comment]
I agree @Carminiumn that it would be better if we redirected to Safari. I also want to figure out how to fix it so it doesn't let override our current auth screen... I will try to look into it before merging by making a new branch and trying to slowly add the code to it.

**Comment by Carminiumn** [comment]
Copy the method of resolving the auth screen and our storyboard, as I send in Discord:

1. Create a `TabViewController` cocoa touch file that inherit from `UITabBarController` and link it to our tab bar controller, also give the tab bar controller a storyboard identifier (could be same as the cocoa touch file)
2. In the `ViewController` file, there is a function called `updateViewBasedOnConnected()`. Delete all lines in the first `if` statement (before `else`), and add:

```swift
let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
let tabViewController = storyBoard.instantiateViewController(withIdentifier: "TabViewController") as! TabViewController
self.present(tabViewController, animated: true, completion: nil)
```
and end up the function will be like

```swift
func updateViewBasedOnConnected() {
    if appRemote.isConnected == true {
        let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let tabViewController = storyBoard.instantiateViewController(withIdentifier: "TabViewController") as! TabViewController
        self.present(tabViewController, animated: true, completion: nil)
    } else { //show login
        disconnectButton.isHidden = true
        connectButton.isHidden = false
        connectLabel.isHidden = false
        imageView.isHidden = true
        trackLabel.isHidden = true
        pauseAndPlayButton.isHidden = true
    }
}
```

This basically a wild way that just tells the app to present our tab bar controller if the user has logged in.
I can’t figure a way to delete all irrelevant code in `ViewController.swift` in the auth branch. I'm pretty sure the code contains a player that will play the user’s last played song, which is unnecessary and annoying

**Comment by Radicitus** [comment]
Stale branch with old code

**Pull request closed without merging**
